version: '3.8'
services:
  web:
    build:
      context: ./src
    container_name: ctf-web
    environment:
      - FLAG=TCC{F4KE_FLAG_FOR_TESTING}
    volumes:
      - ./src:/var/www/html
    ports:
      - "23455:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: ctf-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ctf
      MYSQL_USER: user      
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ctf-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: debug
      PMA_PASSWORD: debugpass
    ports:
      - "23456:80"
    depends_on:
      - db

volumes:
  db_data:
    driver: local
